### ISSUE TITLE
High RAM usage when training

### ISSUE THREAD

**Issue by SilvesterYu** [jac99/MinkLoc3Dv2#4]
Hi, thanks for your amazing work! 

I tried running train.py but encountered a problem with too much RAM usage. There are about 40GB RAM on my machine, but even before the first epoch finished, it already ran out. I decreased the `batch_split_size` as suggested, but the still ran into the same problem.

I checked the memroy usage of each part inside `do_train()`, seems like the problem is with `make_dataloaders()` in `dataset_utils.py` , which consumes a lot of memory.

Could I please know how much RAM train.py actually takes, and if there are possible solutions to my problem? Thanks in advance!

**Comment by jac99** [comment]
Hi, I've trained the model on 64 GB server. To limit the RAM usage, you may try to decrease the number of works in the config file (config_baseline.txt and config_refined.txt in config folder). Instead of using 8 workers, try to use 4 workers and see if the usage of RAM has decreased. Each instance of dataset (and there's one instance per each worker) requires significant amount of RAM.

**Comment by SilvesterYu** [comment]
Hi, thanks for your reply. I found that it was because dataset.queries[label]['positives'] wasn't converted to a bitarray in the `TrainingDataset` object. I moved the `preprocess_queries()` function from MinkLoc3D-SI into it and it worked.
